#pragma once

#include "basehandle.hpp"
#include "CGameMovement.hpp"
#include "checksum_crc.hpp"
#include "ClientClass.hpp"
#include "CMoveData.hpp"
#include "CUserCmd.hpp"
#include "dt_recv.hpp"
#include "IBaseClientDLL.hpp"
#include "IClientEntityList.hpp"
#include "IClientMode.hpp"
#include "ICvar.hpp"
#include "IEngineTrace.hpp"
#include "IGameEvent.hpp"
#include "IMemAlloc.hpp"
#include "input.hpp"
#include "IPrediction.hpp"
#include "ISurface.hpp"
#include "IVDebugOverlay.hpp"
#include "IVEngineClient.hpp"
#include "matrix.hpp"
#include "studio.hpp"
#include "studiorender.hpp"
#include "UtlVector.hpp"

#include "netvar/netvar.hpp"
#include "interfaces/interfaces.hpp"

#include "Entity.hpp"
