#pragma once
#include <windows.h>
#include <cstdint>
#include <thread>
#include <chrono>
#include <stdio.h> 
#include <stdlib.h> 
#include <algorithm>
#include <string>
#include <intrin.h>
#include <d3d9.h>
#include <d3dx9.h>
#include <iostream>
#include <fstream>
#include <ShlObj.h>
#include <filesystem>

#include "features/include.hpp"
#include "frame/frame.hpp"
#include "globals/globals.hpp"
#include "hooks/hooks.hpp"
#include "input/input.hpp"
#include "math/include.hpp"
#include "menu/menu.hpp"
#include "renderer/includes.hpp"
#include "sdk/include.hpp"
#include "util/include.hpp"
#include "vars/vars.hpp"
